### PR TITLE
Fix Vue 2.7 compatibility

### LINKED ISSUE #82: Incompatibility with vue 2.7
After upgrading to `vue:2.7`, [which has composition-api built in](https://blog.vuejs.org/posts/vue-2-7-naruto.html), I started getting this compilation error when running my app:

```
 ERROR  Failed to compile with 1 error                                                                                                                                 12:19:59 PM

 error  in ./node_modules/vue-concurrency/dist/vue2/vue-concurrency.module.js

Module not found: Error: Can't resolve '@vue/composition-api' in '/home/micael/code/webapp/node_modules/vue-concurrency/dist/vue2'

ERROR in ./node_modules/vue-concurrency/dist/vue2/vue-concurrency.module.js 1:0-140
Module not found: Error: Can't resolve '@vue/composition-api' in '/home/micael/code/webapp/node_modules/vue-concurrency/dist/vue2'
 @ ./node_modules/vue-concurrency/dist/index.module.js 1:0-45 1:0-45
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/form/CFileUpload.vue?vue&type=script&lang=ts& 5:0-42 9:26-33
 @ ./src/components/form/CFileUpload.vue?vue&type=script&lang=ts& 1:0-252 1:268-271 1:273-522 1:273-522
 @ ./src/components/form/CFileUpload.vue 2:0-63 3:0-58 3:0-58 9:2-8
 @ ./src/components/ sync [A-Z]\w+\.(vue%7Cjs)$ ./form/CFileUpload.vue
 @ ./src/main.ts 99:21-81
```

Is there anything I'm missing to make this work? Or is `vue-concurrency` incompatible with `vue:2.7`?

### PR DESCRIPTION
**Pull request by Hawxy**
Removes the scope from the reactive object, fixing the `RangeError: Maximum call stack size exceeded` exception.

Note: I'm running the latest version of npm resulting in the package-lock being rebuilt, apologies for the diff size.

Fixes #82

### CODE REVIEW

**Comment by MartinMalinda** [comment]
Thanks! This looks promising. Good catch 👏 

No need to fix tests here btw. Once we know it's working in 2.7, we can remove support for Vue < 2.7 remove the separate builds for Vue 2 and Vue 3 and even the separate test runs.

**Comment by Hawxy** [comment]
No worries. Travis appears unhappy with the new package-lock format & Vuepress with the composition-api removal so you may want to cherry pick this into whichever branch you want to test this in :)

**Comment by Hawxy** [comment]
@MartinMalinda I've pushed up a new version that tests against the v4 branch, is passing for myself locally. Just used `vue-demi` so I didn't need to change the test infrastructure.

**Comment by MartinMalinda** [comment]
@Hawxy that's probably the optimal path forward here, thanks a lot. I've tried `vue-demi` once before and I couldn't make somthing work with it, maybe the test suite, I'm not sure anymore.

I'll check more in detail soon, but it seems with this it will be possible to finally fully release `v4`.

**Comment by dschmidt** [comment]
Hey @MartinMalinda,

is there any chance to have at least another prerelease with this anytime soon?

**Comment by Hawxy** [comment]
This is also a blocker for my team so getting this in as soon as possible would be ideal :)

**Comment by MartinMalinda** [comment]
I'll be checking it this week, maybe tomorrow. Will let you know here once i have a prerelease, if it works for you, I'll do a new classic release finally.Sent from my iPhoneOn 7. 11. 2022, at 10:32, JT ***@***.***> wrote:﻿
This is also a blocker for my team so getting this in as soon as possible would be ideal :)

**Comment by dschmidt** [comment]
I've played around with the PR and it works fine for me with Vue 2.7. Thanks a lot, @Hawxy!

Just a little heads up for anyone coming accross this: Although vue-demi (in general) can work with Vue < 2.7, this PR does not - so you need to switch to Vue 2.7 and the new vue-concurrency version at the same time.

**Comment by Hawxy** [comment]
> it works fine for me with Vue 2.7.

Awesome 👍 

> Although vue-demi (in general) can work with Vue < 2.7, this PR does not

Because I didn't change any library internals to use vue-demi, I just used it so I could reuse the test infrastructure created for Vue 3. I'm aware it didn't used to work for this project, but someone might want to try again.

**Comment by dschmidt** [comment]
Yep, I understand - just wanted to point it out for anyone trying this or the new release :)

**Comment by MartinMalinda** [comment]
I've also tested this in a Vue 2.7 app and it works well. It's released in 4.0.0. Thanks @Hawxy and all others testing it!

**Pull request merged**
