### PR TITLE
Move vitepress to devDependencies, bump it to official v1.x.x release

### LINKED ISSUE #104: Why is Vitepress a normal dep?
It loads soooo many other deps, thats insane for such a small library!?

### PR DESCRIPTION
**Pull request by pascalwengerter**
Fixes #104, also bumps Vitepress since it was still using a `rc` version.

I'm not a Vitepress expert by any means, but the only difference I could spot was a slightly larger top margin on the pages? Vitepress [changelog](https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md) notes two (unrelated) breaking changes since the formerly used release

### CODE REVIEW

**Comment by pascalwengerter** [comment]
(Side note: Also not sure if `docs/.vitepress/` or `docs/.vitepress/cache` necessarily need to be checked in with the rest of the repo?)

**Comment by MartinMalinda** [comment]
Thanks a lot! I'm checking the deploy preview and it looks all right 👍 

> (Side note: Also not sure if `docs/.vitepress/` or `docs/.vitepress/cache` necessarily need to be checked in with the rest of the repo?)

Ahh, judging by the number of lines changed  (`+14,278 −2,023`), I guess no. Maybe I haven't fully followed some install instructions, it looks like the `cache` is something that's supposed to go to the `gitignore`.

Probably should be exactly the same as here: https://github.com/vitejs/vite/blob/main/.gitignore#L9

**Comment by pascalwengerter** [comment]
Let me update the PR then ;)

**Comment by MartinMalinda** [comment]
Looks great, thanks a lot 🙏

**Pull request merged**
